### ISSUE TITLE
PiFS installs large volumes of objectionable content and copyright violations

### ISSUE THREAD

**Issue by maplealmond** [philipl/pifs#2]
While parsing the contents of PiFS I was shocked to find that it contained a large amount of objectionable and pornographic content.  There are a set of indexes (which I won't reproduce here for legal reasons) point to files which I believe may cause the user to face serious liability if PiFS is discovered on their system.

In addition, there are indexes which contain numerous copyrighted materials, as well as keys to break various DRM schemes.  I believe that the use of PiFS may constitute a DMCA violation.

**Comment by Konard** [comment]
> It's pretty easy to prove, mathmathically, that the metadata size will be larger than the data, regardless of implementation.

Unless metadata itself stored inside pi, and there is a standard metadata format. Metadata stored in pi is a key to read actual data, metadata can optionally store a filename. If done so, the only thing to get actual data that needed is a standard algorighm and an actual first index there the metadata starts in pi. Ones and for all this will be named ultimate compression algorithm.

**Comment by TwoD** [comment]
If filename is only indirectly known by an index in Pi, how do we find the actual data or additional metadata for "foo.txt" when requested?

Back to the original issue of copyright; Unless all of Pi's decimals are physically on the disk, it doesn't matter if anyone claims copyright on something. You wouldn't have the data, you would just know how to retrieve it. Like torrents only pointing to who has data matching some criteria.

**Comment by vurso** [comment]
Is it possible to accidently open up a portal to another dimension due to some type of metadata soup scenario?
