### ISSUE TITLE
Security : Everybody has my files

### ISSUE THREAD

**Issue by jmaris** [philipl/pifs#49]
PiFS sets a dangerous precedant ! thousands of PiFS Users have **ALL** my files!
_**THIS IS A PRIVACY NIGHTMARE AND AN OUTRAGE !**_

**Comment by hadi77ir** [comment]
It is ideal for sharing files across systems, but if you want security, try GPG and encrypt your data before saving! So, if someone has your file, he will need the key to decrypt it.

**Comment by lammbraten** [comment]
Have done that, but now my private key is stored in there. It even get worse!

**Comment by hadi77ir** [comment]
Um, I think you shouldn't have stored your private key there...

Note: For others to have access to your files, they must have a copy of your "metadata" directory. So I don't think we can call it a "privacy nightmare"!

**Comment by foobarto** [comment]
Since Pi is a constant it already has all your files that you ever had and every will have :)

**Comment by undrskr** [comment]
That's funny, but noone will find it unless they know the address. Since pi is infinite, you'll have a hard time bruteforcing it.

**Comment by jmaris** [comment]
I may need to open a new bug report about people having _no sense of humour_
